openapi: 3.0.3
info:
  title: Cloud-iot
  description: Api definition for cloud iot service
  version: 1.0.0
paths: {}

components:
  schemas:
    Alfanum:
      type: object
      properties:
        spec:
          type: integer
        next:
          type: string
