openapi: 3.0.3
info:
  title: Title
  description: Title
  version: 1.0.0
servers:
  - url: 'https'
paths: {}

components:
  schemas:
    LightCmd:
      type: object
      properties:
        onOff:
          type: boolean
    EnvInfo:
      type: object
      properties:
        temperature:
          type: number
        humidity:
          type: number
        pressure:
          type: number
    MqttMessage:
      type: object
      properties:
        messageId:
          type: integer
        type:
          type: string
        payload:
          type: object