openapi: 3.0.3
info:
  title: Mqtt messages defininition
  description: Definition of messages running between service and device over mqtt
  version: 1.0.0
paths: { }

components:
  schemas:
    ModelDouble:
      type: number
      format: double
    LightCmd:
      type: object
      properties:
        onOff:
          type: boolean
    EnvInfo:
      type: object
      properties:
        temperature:
          $ref: '#/components/schemas/ModelDouble'
        humidity:
          $ref: '#/components/schemas/ModelDouble'
        pressure:
          $ref: '#/components/schemas/ModelDouble'
    StatusResp:
      type: object
      properties:
        envInfo:
          $ref: '#/components/schemas/EnvInfo'
        light:
          type: boolean
        doors:
          type: boolean
        heater:
          $ref: '#/components/schemas/Heater'
        fan:
          type: boolean
        humidifier:
          type: boolean
    Heater:
      type: object
      properties:
        onOff:
          type: boolean
        setTemp:
          type: number
          format: double
    UpdateRequest:
      type: object
      properties:
        light:
          type: boolean
        heater:
          $ref: '#/components/schemas/Heater'
        fan:
          type: boolean
        humidifier:
          type: boolean
    MessageType:
      type: string
      enum: [ PING, OK, ERROR, AUTHORIZE, ENV_INFO, LIGHT_CMD, STATUS_REQ, STATUS_RESP, UPDATE_REQ ]
    MqttSystemMessage:
      type: object
      properties:
        messageId:
          type: integer
          format: int64
        type:
          $ref: '#/components/schemas/MessageType'
        payload:
          type: object