openapi: 3.0.3
info:
  title: Title
  description: Title
  version: 1.0.0
servers:
  - url: 'https'
paths: {}

components:
  schemas:
    ModelDouble:
      type: number
      format: double
    LightCmd:
      type: object
      properties:
        onOff:
          type: boolean
    EnvInfo:
      type: object
      properties:
        temperature:
          $ref: '#/components/schemas/ModelDouble'
        humidity:
          $ref: '#/components/schemas/ModelDouble'
        pressure:
          $ref: '#/components/schemas/ModelDouble'
    MessageType:
      type: string
      enum: [ PING, OK, ERROR, ENV_INFO, LIGHT_CMD ]
    MqttSystemMessage:
      type: object
      properties:
        messageId:
          type: integer
          format: int64
        type:
          $ref: '#/components/schemas/MessageType'
        payload:
          type: object