server:
  port: 9000

spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url:  ${POSGTRES_URL:jdbc:postgresql://localhost:5432/cloud_iot}
    username: ${POSGTRES_USER:postgres}
    password: ${POSGTRES_PASSWORD:postgres}

mqtt:
  broker: ${MQTT_BROKER:tcp://localhost:1883}
  username: ${MQTT_USER:service}
  password: ${MQTT_PASSWORD:master}
  clientId: ${MQTT_CLIENT_ID:iot_service}
