server:
  port: 9060
  ssl:
    key-store: classpath:keystore.p12
    key-store-password: springboot
    keyStoreType: PKCS12
    keyAlias: tomcat

spring:
  autoconfigure:
    exclude: >
      org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration,
      org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration,
      org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration, 
      org.springframework.boot.autoconfigure.jdbc.DataSourceTransactionManagerAutoConfiguration

mqtt:
  broker: ${MQTT_BROKER:tcp://localhost:1883}
  username: ${MQTT_USER:service}
  password: ${MQTT_PASSWORD:master}
  clientId: ${MQTT_CLIENT_ID:iot_service}

simulator:
  backend:
    url: ${IOT_BACKEND:https://localhost:9000}

logging:
  level:
    pl.terra: DEBUG

state-file: ${STATE_FILE:./src/main/resources/sim}
example-devices: ${EXAMPLE_DEVICES:./src/main/resources/devices/excample_device_list.json}