server:
  port: 9000

mqtt:
  broker: ${MQTT_BROKER:tcp://localhost:1883}
  username: ${MQTT_USER:service}
  password: ${MQTT_PASSWORD:master}
  clientId: ${MQTT_CLIENT_ID:iot_service}

logging:
  level:
    com:
      baeldung: TRACE