server:
  port: 9000

spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url:  ${POSTGRES_URL:jdbc:postgresql://localhost:5432/cloud_iot}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:postgres}

logging:
  level:
    pl.terra: ${LOGGING_LEVEL:DEBUG}

mqtt:
  broker: ${MQTT_BROKER:tcp://localhost:1883}
  username: ${MQTT_USER:service}
  password: ${MQTT_PASSWORD:master}
  clientId: ${MQTT_CLIENT_ID:iot_service}
